quarkus:
  mongodb:
    connection-string: ${MONGODB_URI}
    database: admin
    devservices:
      enabled: false
  redis:
    hosts: ${REDIS_HOST}
    max-pool-size: 200
    devservices:
      enabled: false
  native:
    compression:
      level: 8
    application:
      name: languages-api
    swagger-ui:
      always-include: true
  log:
    console:
      format: '%d{HH:mm:ss} %-5p traceId=%X{traceId}, parentId=%X{parentId}, spanId=%X{spanId}, sampled=%X{sampled} [%c{2.}] (%t) %s%e%n'
      json:
        key-overrides: timestamp=time,message=msg,logger_Name=logger,thread_name=thread
        excluded-keys:
          - loggerClassName
          - processName
          - sequence
          - ndc
          - threadId
        date-format: yyyy-MM-dd'T'HH:mm:ss.SSSS
        additional-field:
          app:
            type: string
            value: languages-api

  index-dependency:
    languages-api-data-provider:
      group-id: br.com.alura
      artifact-id: data-provider
    languages-api-domain:
      group-id: br.com.alura
      artifact-id: domain