quarkus:
  mongodb:
    connection-string: ${MONGODB_URI}
    database: admin
    devservices:
      enabled: false
  redis:
    hosts: ${REDIS_HOST}
    max-pool-size: 200
    devservices:
      enabled: false
  native:
    compression:
      level: 8
    application:
      name: languages-api
    swagger-ui:
      always-include: true
  log:
    console:
      format: '%d{HH:mm:ss} %-5p traceId=%X{traceId}, parentId=%X{parentId}, spanId=%X{spanId}, sampled=%X{sampled} [%c{2.}] (%t) %s%e%n'

  index-dependency:
    languages-api-data-provider:
      group-id: br.com.alura
      artifact-id: data-provider
    languages-api-domain:
      group-id: br.com.alura
      artifact-id: domain