apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: api-micronaut-database-catalog-hpa
  namespace: corp-architecture
  labels:
    app: api-micronaut-database-catalog
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-micronaut-database-catalog-deploy
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 500
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 250