name: languages-api-ci
on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io

jobs:
  container_image:
    name: Update Container Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Login Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}
      - name: Build and push Container Image
        run: |
          docker build -t ${{ env.REGISTRY }}/${{ github.actor }}/languages-api:${{ github.sha }} -f Containerfile .
          docker push ${{ env.REGISTRY }}/${{ github.actor }}/languages-api:${{ github.sha }}
