name: languages-api-ci
on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io

jobs:
  container_image:
    name: Update Container Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Login Container registry
        uses: docker/login-action
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
          uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
          with:
            context: .
            push: true
            tags: ${{ env.REGISTRY }}/${{ github.actor }}/languages-api:${{ github.sha }}
            file: Containerfile
